name: CI
on:
  workflow_dispatch:
    inputs:
      tag:
        description: '要发布的版本标签 (例如: v1.2.3)'
        required: true
        type: string
jobs:
  build-1:
    runs-on: windows-2022
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./.github/actions/stage/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./.github/actions/stage/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: false
          from_artifact: false
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-2:
    needs: build-1
    if: needs.build-1.outputs.finished == 'false'
    runs-on: windows-2022
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./.github/actions/stage/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./.github/actions/stage/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-1.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-3:
    needs: build-2
    if: needs.build-2.outputs.finished == 'false'
    runs-on: windows-2022
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./.github/actions/stage/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./.github/actions/stage/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-2.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-4:
    needs: build-3
    if: needs.build-3.outputs.finished == 'false'
    runs-on: windows-2022
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./.github/actions/stage/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./.github/actions/stage/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-3.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-5:
    needs: build-4
    if: needs.build-4.outputs.finished == 'false'
    runs-on: windows-2022
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./.github/actions/stage/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./.github/actions/stage/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-4.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-6:
    needs: build-5
    if: needs.build-5.outputs.finished == 'false'
    runs-on: windows-2022
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./.github/actions/stage/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./.github/actions/stage/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-5.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-7:
    needs: build-6
    if: needs.build-6.outputs.finished == 'false'
    runs-on: windows-2022
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./.github/actions/stage/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./.github/actions/stage/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-6.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-8:
    needs: build-7
    if: needs.build-7.outputs.finished == 'false'
    runs-on: windows-2022
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./.github/actions/stage/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./.github/actions/stage/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-7.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-9:
    needs: build-8
    if: needs.build-8.outputs.finished == 'false'
    runs-on: windows-2022
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./.github/actions/stage/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./.github/actions/stage/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-8.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-10:
    needs: build-9
    if: needs.build-9.outputs.finished == 'false'
    runs-on: windows-2022
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./.github/actions/stage/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./.github/actions/stage/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-9.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-11:
    needs: build-10
    if: needs.build-10.outputs.finished == 'false'
    runs-on: windows-2022
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./.github/actions/stage/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./.github/actions/stage/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-10.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-12:
    needs: build-11
    if: needs.build-11.outputs.finished == 'false'
    runs-on: windows-2022
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./.github/actions/stage/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./.github/actions/stage/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-11.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-13:
    needs: build-12
    if: needs.build-12.outputs.finished == 'false'
    runs-on: windows-2022
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./.github/actions/stage/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./.github/actions/stage/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-12.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-14:
    needs: build-13
    if: needs.build-13.outputs.finished == 'false'
    runs-on: windows-2022
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./.github/actions/stage/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./.github/actions/stage/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-13.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-15:
    needs: build-14
    if: needs.build-14.outputs.finished == 'false'
    runs-on: windows-2022
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./.github/actions/stage/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./.github/actions/stage/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-14.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}
  build-16:
    needs: build-15
    if: needs.build-15.outputs.finished == 'false'
    runs-on: windows-2022
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "C:\ungoogled-chromium-windows" -Recurse
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./.github/actions/stage/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./.github/actions/stage/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-15.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}

  publish-release:
    needs: [build-1, build-2, build-3, build-4, build-5, build-6, build-7, build-8, build-9, build-10, build-11, build-12, build-13, build-14, build-15, build-16]
    if: always() && contains(join(needs.*.outputs.finished), 'true')
    runs-on: ubuntu-latest
    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: chromium
      - name: Publish release
        id: publish
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          fail_on_unmatched_files: true
          files: |
            ungoogled-chromium*
    outputs:
      assets: ${{ steps.publish.outputs.assets }}
